### ISSUE TITLE
Error at Edit tweet 

### ISSUE THREAD

**Issue by WurmPeter** [zachdaniel/twitter#1] opened 2023-02-05 20:16 UTC
Hello,

I try to learn Ash from that app - so thanks for creating it.
It's not so easy for me because the edit/new pages are in a modal and not their own pages, but I try my best... 

When I try to edit a tweet - not from the index page, but from the show page - I get an error:
"no function clause matching in TwitterWeb.TweetLive.FormComponent.update/2"

**Comment by zachdaniel** [comment] 2023-02-06 06:01
Hey there! This is interesting, I don't see that same thing on my machine. Could you show more of the error message?

**Comment by WurmPeter** [comment] 2023-02-06 18:12
Hello,

That's odd... 

To be sure, I click on this "Edit tweet"-link:
![Screenshot 2023-02-06 19 08 57](https://user-images.githubusercontent.com/54888064/217051475-28421345-34cb-4b96-8366-647e3e65b334.png)

First i get a red alert box in the top right corner saying "We can't find the internet. Attempting to reconnect" and then the error page.  

This the output in the terminal:

[error] #PID<0.745.0> running Phoenix.Endpoint.SyncCodeReloadPlug (connection #PID<0.744.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /tweets/ffd7fe04-de0d-4f12-8560-d17054ee3fc5/show/edit
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in TwitterWeb.TweetLive.FormComponent.update/2
        (twitter 0.1.0) lib/twitter_web/live/tweet_live/form_component.ex:32: TwitterWeb.TweetLive.FormComponent.update(%{action: :edit, id: "ffd7fe04-de0d-4f12-8560-d17054ee3fc5", navigate: "/tweets/ffd7fe04-de0d-4f12-8560-d17054ee3fc5", title: "Edit Tweet", tweet: #Twitter.Tweets.Tweet<visible_as_friend: #Ash.NotLoaded<:calculation>, visible_to: #Ash.NotLoaded<:calculation>, liked_by_user: #Ash.NotLoaded<:calculation>, like_count: #Ash.NotLoaded<:aggregate>, author_email: #Ash.NotLoaded<:aggregate>, likes: #Ash.NotLoaded<:relationship>, author: #Ash.NotLoaded<:relationship>, __meta__: #Ecto.Schema.Metadata<:loaded, "tweets">, id: "ffd7fe04-de0d-4f12-8560-d17054ee3fc5", text: "We might make a party!", visibility: :public, inserted_at: ~U[2023-02-05 19:44:04.990814Z], updated_at: ~U[2023-02-05 19:44:04.990814Z], author_id: "db80aa74-53ba-49a0-85e4-803785cd2af4", aggregates: %{}, calculations: %{}, __order__: nil, ...>}, #Phoenix.LiveView.Socket<id: "phx-F0FNuKphZnvA1wAm", endpoint: TwitterWeb.Endpoint, view: TwitterWeb.TweetLive.Show, parent_pid: nil, root_pid: nil, router: TwitterWeb.Router, assigns: %{__changed__: %{flash: true}, flash: %{}, myself: %Phoenix.LiveComponent.CID{cid: 1}}, transport_pid: nil, ...>)
        (phoenix_live_view 0.18.11) lib/phoenix_live_view/utils.ex:428: Phoenix.LiveView.Utils.maybe_call_update!/3
        (phoenix_live_view 0.18.11) lib/phoenix_live_view/diff.ex:635: anonymous fn/5 in Phoenix.LiveView.Diff.render_pending_components/6
        (elixir 1.14.1) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
        (stdlib 4.1.1) maps.erl:411: :maps.fold_1/3
        (phoenix_live_view 0.18.11) lib/phoenix_live_view/diff.ex:609: Phoenix.LiveView.Diff.render_pending_components/6
        (phoenix_live_view 0.18.11) lib/phoenix_live_view/diff.ex:145: Phoenix.LiveView.Diff.render/3
        (phoenix_live_view 0.18.11) lib/phoenix_live_view/static.ex:252: Phoenix.LiveView.Static.to_rendered_content_tag/4
        (phoenix_live_view 0.18.11) lib/phoenix_live_view/static.ex:135: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.18.11) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
        (phoenix 1.7.0-rc.2) lib/phoenix/router.ex:425: Phoenix.Router.__call__/5
        (twitter 0.1.0) lib/twitter_web/endpoint.ex:1: TwitterWeb.Endpoint.plug_builder_call/2
        (twitter 0.1.0) lib/plug/debugger.ex:136: TwitterWeb.Endpoint."call (overridable 3)"/2
        (twitter 0.1.0) lib/twitter_web/endpoint.ex:1: TwitterWeb.Endpoint.call/2
        (phoenix 1.7.0-rc.2) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (plug_cowboy 2.6.0) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
        (cowboy 2.9.0) /home/nefcairon/Projekte/twitter/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /home/nefcairon/Projekte/twitter/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) /home/nefcairon/Projekte/twitter/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

**Comment by zachdaniel** [comment] 2023-02-06 18:14
Sorry, you're totally right, I should have read your report more closely :)
> from the show page

Missed that bit.

**Comment by zachdaniel** [comment] 2023-02-06 18:18
Thanks for the report! The issue is fixed in main.

**Closed as completed** 2023-02-06 18:18 UTC
